### ISSUE TITLE
Unable to run on emulator

### ISSUE THREAD

**Issue by Moataz-E** [SimonMarquis/AR-Toolbox#2]
Hi Simon,

I am looking to play around with your repository but when I try to run it on an emulator the app crashes.

**API:** 24
**Target:** Android 7.0 (Google Play)
**CPU**: x86

Attached is the full error log and below is a summary of the main error:

> Process: fr.smarquis.ar_toolbox, PID: 2285
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.smarquis.ar_toolbox/fr.smarquis.ar_toolbox.SceneActivity}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.google.ar.sceneform.ArSceneView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.google.ar.sceneform.ArSceneView
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.google.ar.sceneform.ArSceneView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:158)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at fr.smarquis.ar_toolbox.SceneActivity.onCreate(SceneActivity.kt:61)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.IllegalStateException: Couldn't create Engine
        at com.google.android.filament.Engine.create(Engine.java:67)
        at com.google.ar.sceneform.rendering.EngineInstance.createEngine(EngineInstance.java:85)
        at com.google.ar.sceneform.rendering.EngineInstance.getEngine(EngineInstance.java:39)
        at com.google.ar.sceneform.rendering.Renderer.initialize(Renderer.java:505)
        at com.google.ar.sceneform.rendering.Renderer.<init>(Renderer.java:106)
        at com.google.ar.sceneform.SceneView.initialize(SourceFile:78)
        at com.google.ar.sceneform.SceneView.<init>(SourceFile:21)
        at com.google.ar.sceneform.ArSceneView.<init>(SourceFile:11)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:645) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377) 
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555) 
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161) 
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:158) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312) 
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106) 
        at fr.smarquis.ar_toolbox.SceneActivity.onCreate(SceneActivity.kt:61) 
        at android.app.Activity.performCreate(Activity.java:6662) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 

[artoolbox_error.txt](https://github.com/SimonMarquis/AR-Toolbox/files/4002822/artoolbox_error.txt)

**Comment by Moataz-E** [comment]
It appears to be an issue with getting OpenGL to work. I've bypassed this by running the app on a physical developer phone instead.
