### ISSUE TITLE
App Closes Suddenly with AR Session Error

### ISSUE THREAD

**Issue by lumec** [SimonMarquis/AR-Toolbox#88]
**Error Message:** After I open the app, it closes itself suddenly, and a toast message pops up with the following error: "Failed to create AR session."

**Steps to Reproduce:**

    Open the app.
    The app immediately closes, and the error message appears.

**Expected Behavior:** The app should open without any issues, and the AR session should be created successfully.

**Actual Behavior:** The app abruptly closes, and the error message "Failed to create AR session" is displayed in a toast.

**Device and OS Information:** I'm using a motorola g30 running Android 12.

**App Version:** I'm experiencing this issue in app version 1.13.0, 1.12.0, 1.11.0, 1.10.0.

**Logcat Error:**

```
E  E0000 00:00:1698935154.698061   11469 error_policy_util.cc:263] 
################ ARCore Native Error ##################
BUILD_CHANGELIST:569645839
BUILD_BASELINE_CHANGELIST:566808989
################### Stack Trace Begin ################
ARCoreError: third_party/arcore/ar/planar_targets/augmented_image_database_utils.cc:67	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/planar_targets/augmented_image_database_utils.cc?g=0&l=67
ARCoreError: third_party/arcore/ar/core/c_api/augmented_image_database_c_api.cc:134	https://cs.corp.google.com/piper///depot/google3/third_party/arcore/ar/core/c_api/augmented_image_database_c_api.cc?g=0&l=134
################### Stack Trace End #################

################### Undecorated Trace Begin  #################
INVALID_ARGUMENT: 
ARCoreError: third_party/arcore/ar/planar_targets/augmented_image_database_utils.cc:67
Insufficient image quality for added image [type.googleapis.com/util.ErrorSpacePayload='ArStatusErrorSpace::AR_ERROR_IMAGE_INSUFFICIENT_QUALITY']
=== Source Location Trace: === 
third_party/arcore/ar/core/status.cc:165
third_party/arcore/ar/planar_targets/augmented_image_database_utils.cc:67

################### Undecorated Trace End  #################
E  Failed to open APK '/data/app/~~clvHISspU8e0pCchfRI7ZQ==/fr.smarquis.ar_toolbox-7w2iJRwrzLkREhGvPQ1cxg==/base.apk': I/O error
E  Failed to open APK '/data/app/~~clvHISspU8e0pCchfRI7ZQ==/fr.smarquis.ar_toolbox-7w2iJRwrzLkREhGvPQ1cxg==/split_config.arm64_v8a.apk': I/O error
E  Failed to open APK '/data/app/~~clvHISspU8e0pCchfRI7ZQ==/fr.smarquis.ar_toolbox-7w2iJRwrzLkREhGvPQ1cxg==/split_config.en.apk': I/O error
E  Failed to open APK '/data/app/~~clvHISspU8e0pCchfRI7ZQ==/fr.smarquis.ar_toolbox-7w2iJRwrzLkREhGvPQ1cxg==/split_config.xhdpi.apk': I/O error
E  Failed to open APK '/data/app/~~clvHISspU8e0pCchfRI7ZQ==/fr.smarquis.ar_toolbox-7w2iJRwrzLkREhGvPQ1cxg==/base.apk': I/O error
E  failed to add asset path '/data/app/~~clvHISspU8e0pCchfRI7ZQ==/fr.smarquis.ar_toolbox-7w2iJRwrzLkREhGvPQ1cxg==/base.apk'
java.io.IOException: Failed to load asset path /data/app/~~clvHISspU8e0pCchfRI7ZQ==/fr.smarquis.ar_toolbox-7w2iJRwrzLkREhGvPQ1cxg==/base.apk
	at android.content.res.ApkAssets.nativeLoad(Native Method)
	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:455)
	at android.app.ResourcesManager.access$000(ResourcesManager.java:73)
	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:169)
	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:531)
	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:613)
	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:665)
	at android.app.ResourcesManager.createResources(ResourcesManager.java:1018)
	at android.app.ResourcesManager.getResources(ResourcesManager.java:1121)
	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2466)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1751)
	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1506)
	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3036)
	at android.content.pm.PackageItemInfo.loadUnbadgedIcon(PackageItemInfo.java:303)
	at com.android.systemui.toast.SystemUIToast.getBadgedIcon(SystemUIToast.java:284)
	at com.android.systemui.toast.SystemUIToast.inflateToastView(SystemUIToast.java:198)
	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:90)
	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:77)
	at com.android.systemui.toast.ToastFactory.createToast(ToastFactory.java:78)
	at com.android.systemui.toast.ToastUI.lambda$showToast$0(ToastUI.java:115)
	at com.android.systemui.toast.ToastUI.$r8$lambda$w_gPCh3F8Xxn1jN4lkQZoUci71c(Unknown Source:0)
	at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda1.run(Unknown Source:16)
	at com.android.systemui.toast.ToastUI.showToast(ToastUI.java:142)
	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:1610)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:329)
	at android.app.ActivityThread.main(ActivityThread.java:8058)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)

```

**Comment by SimonMarquis** [comment]
Hi @lumec, thanks for the report.
It seems like this issue comes from a recent update of the Google Play Services for AR.
I'll try to fix the issue next week.

**Comment by SimonMarquis** [comment]
Well, it's been a week and I feel like they will never answer.
I'll merge this a publish a new version today.

**Comment by SimonMarquis** [comment]
@lumec the app has been updated on Google Play, and you should receive it soon.
